### ISSUE TITLE
Feature: User can upload an image

### ISSUE THREAD

**Issue by brij8** [brij8/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click upload button, choose an image file, and load selected image onto the screen.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click to upload your own images into this site.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project_features01](https://user-images.githubusercontent.com/42279790/156074739-129d603a-7eea-4a64-becd-afc7acae34ce.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] lay down foundational HTML & CSS (for header, button, and image display)
     - [x] basic body & header done and styled correctly
     - [x] sections blocked out
     - [x] src img preview fitting nicely in display area
     - [x] button type styled
     - [x] upload button in place
- [x] upload button exists and opens file explorer (or equivalent)
     - [x] add event listener for click on upload button
     - [x] on click, open file explorer 
     - [x] ...this is complicated
- [x] selected image loads into display area
     - [x] selected image from explorer is assigned to img src
- [x] establish breaks for desktop/mobile scaling and related style changes (600px w?)
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
