### ISSUE TITLE
Feature: User can generate color palettes

### ISSUE THREAD

**Issue by brij8** [brij8/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the Generate button and watch the 5 colors of the palette change with each click.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click Generate to see different palettes based on my image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project_features02](https://user-images.githubusercontent.com/42279790/156075397-0216f8c3-f643-4370-b044-d322e908d9a0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] clicking generate button refreshes swatches/palette with a new API request/response
- [x] main palette, 5 blank swatch-containers for colors with color-codes & hold icon shows on page load
- [x] generate & save buttons
 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
