### ISSUE TITLE
Feature: User can adjust each color and/or hold colors

### ISSUE THREAD

**Issue by brij8** [brij8/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can adjust each color, or hold colors to not change on next generation.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Select colors to hold when generating and adjust each color prior to saving.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project_features03](https://user-images.githubusercontent.com/42279790/156076136-91016ad0-3181-4563-8bef-2fb323afbf2d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] clicking swatch opens color picker
- [x] closing color picker assigns color & code to swatch
- [x] hold buttons toggling style
- [x] hold icons assign color-code to corresponding input array index as integers
- [x] input & codes works for all 5 swatches in palette
- [x] fix palette/tools scaling for longer color-codes 
     - [x] restyle hold button & code placement 
- [x] genPalette() works properly!

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
