### ISSUE TITLE
Feature: User can save palettes

### ISSUE THREAD

**Issue by brij8** [brij8/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Save palettes with optional name, notes, and source filename. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Save your palette with your own name, description, and even the source file.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project_features04](https://user-images.githubusercontent.com/42279790/156076589-4aecb9ae-3f25-4bf1-b81c-217855cd2ba9.png)
![ajax-project_features05](https://user-images.githubusercontent.com/42279790/156076594-d9f9ba89-3223-4926-bf81-08e4990c8b02.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] make and style save-modal
- [ ] save-model opens/interacts/closes properly
- [ ] make and style saved-palettes section
- [ ] saving a palette puts it in saved-palettes
- [ ] saving a palette populates details options properly (name, notes, src-img)
- [ ] can delete palettes from saved-palettes

- [ ] add minimal instructions (make simple icon graphics?)
     - [ ] upload an image for color selection
     - [ ] click swatch to select/adjust a color
     - [ ] use eyedropper in color picker to select colors from your image
     - [ ] clicking generate with no colors = random palette
     - [ ] clicking generate with a/some colors = seeded palette
     - [ ] held swatch position effect results
- [ ] add verbose instructions/details ?
- [ ] colomind.io links

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
